@tpmodul10_1302220009_HostAddress = http://localhost:5167

GET {{tpmodul10_1302220009_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{tpmodul10_1302220009_HostAddress}}/mahasiswa/
Accept: application/json

###